areDevices = [
    "camera",
    "ipcam",
    "netcam",
    "cam",
    "dvr",
    "router",
    "nvr",
    "nvs",
    "video server",
    "video encoder",
    "video recorder",
    "diskstation",
    "rackstation",
    "printer",
    "copier",
    "scanner",
    "switches",
    "modem",
    "switch",
    "gateway",
    "access point"
]

nmapAndZtagDevices = [
    "access point",
    "alarm system",
    "bridge",
    "broadband router",
    "cable modem",
    "cam",
    "camera",
    "copier",
    "diskstation",
    "dsl modem",
    "dsl/cable modem",
    "cable modem"
    "dvr",
    "environment monitor",
    "firewall",
    "fire alarm",
    "game console",
    "gateway",
    "general purpose",
    "hub",
    "hvac",
    "industrial control system",
    "infrastructure router",
    "ipcam",
    "ipmi",
    "kvm",
    "laser printer",
    "light controller",
    "load balancer",
    "media device",
    "modem",
    "nas",
    "netcam",
    "network",
    "nvr",
    "nvs",
    "pbx",
    "pda",
    "phone",
    "power controller",
    "power distribution unit",
    "power monitor",
    "power device",
    "print server",
    "printer",
    "private branch exchange",
    "programmable logic controller",
    "proxy server",
    "rackstation",
    "remote management",
    "router",
    "scada controller",
    "scada frontend",
    "scada gateway",
    "scada router",
    "scada server",
    "scanner",
    "security misc",
    "set top box",
    "set-top box",
    "sign",
    "soho router",
    "solar panel",
    "specialized ",
    "storage misc",
    "switch",
    "switches",
    "telecom misc",
    "terminal",
    "terminal server",
    "tv tuner",
    "usb",
    "video encoder",
    "video recorder",
    "video server",
    "voip adapter",
    "voip phone",
    "voip phone",
    "wap",
    "water flow controller",
    "webcam",
    "wireless modem"
]

devices = list(set(areDevices + nmapAndZtagDevices))
