# encoding: utf-8
vendors = [
    "10duke",
    "1nce",
    "2lementry (amazon web services)",
    "3d hubs",
    "3d robotics",
    "3d systems",
    "3dsignals",
    "3m company",
    "3onedata",
    "3scale (red hat)",
    "3sense technology",
    "3shape",
    "4dage",
    "4ng limited",
    "51hitech",
    "51vr",
    "6wind",
    "75f",
    "99cloud",
    "9solutions",
    "aac technologies 瑞声科技",
    "aaeon technology",
    "aanarr ltd",
    "ab regin",
    "abaco systems",
    "abas",
    "abb",
    "abb stotz kontakt",
    "abc",
    "abiogenix",
    "abivin",
    "ablecloud",
    "abracon",
    "absyz",
    "accent systems",
    "accenture",
    "acces i/o products",
    "access control technologies",
    "accumine technologies ltd.",
    "accure inc",
    "ace pillar",
    "achronix",
    "aclara",
    "acme portable corp.",
    "acnodes corporation",
    "aco recycling",
    "aconex",
    "acromag",
    "acrosser technology",
    "acs motion control",
    "acsip technology corp.",
    "actemium",
    "actility",
    "active semi international, inc.",
    "active-semi international, inc.",
    "actl",
    "acuity brands",
    "acunote",
    "adafruit industries",
    "adamos",
    "adapt-n",
    "adaptive wireless solutions",
    "adata",
    "adb",
    "adbits",
    "addverb",
    "adheretech",
    "adi engineering, inc.",
    "adl embedded solutions inc.",
    "adlink",
    "adlink technology",
    "adrf",
    "adroit technologies",
    "ads-tec gmbh",
    "adtran",
    "aduk gmbh",
    "advanced control systems",
    "advantech",
    "advantech b+b smartworx",
    "advanticsys",
    "aegis mobility",
    "aegis software",
    "aegis technology",
    "aeris communications",
    "aeron systems",
    "aeroscout",
    "aerspace",
    "aevice health",
    "aewin",
    "afimilk",
    "afour technologies",
    "ag leader",
    "agilepq",
    "aginova",
    "agosto",
    "agranat",
    "aibotix (hexagon geosystems)",
    "aic inc.",
    "aic monitor",
    "aicas",
    "aikaan labs",
    "ailytic",
    "aimetis",
    "aimtec",
    "aio robotics",
    "aira tech corp",
    "airbiquity",
    "airly",
    "airm2m",
    "airobotics",
    "airstrip technologies",
    "airtek",
    "airtel",
    "airware",
    "ais automation dresden (s&t ag)",
    "aistorm",
    "akenza ag",
    "akselos",
    "akvelon",
    "alascom services srl",
    "alcatel",
    "alelion",
    "aleph objects",
    "alerton",
    "algarytm",
    "algo engines",
    "algo system",
    "alibaba cloud (aliyun, 阿里云)",
    "alien technology",
    "alinket electronic technology(shanghai) co.,ltd",
    "alleantia",
    "allegion",
    "allegro microsystems",
    "allegro software",
    "allerin",
    "alloy",
    "allseen alliance",
    "allthingstalk",
    "alluvium",
    "allwinner technology",
    "allworx",
    "alnicko development",
    "aloalto",
    "alotcer",
    "alpha & omega semiconductor",
    "alpha wire",
    "alpwise",
    "alt software inc.",
    "altair",
    "altair semiconductors (sony)",
    "altell ltd.",
    "alten calsoft labs",
    "altera corporation",
    "altium limited",
    "altiux innovations",
    "altizon systems",
    "altoros",
    "altran technologies",
    "alyt",
    "amax",
    "amazon robotics (amazon)",
    "amazon web services",
    "ambient devices",
    "ambiq micro",
    "ambyint",
    "amd",
    "american auto-matrix",
    "american megatrends, inc.",
    "american power conversion (schneider electric)",
    "ames adt, inc.",
    "ami ge",
    "amper technologies",
    "amphenol rf",
    "ampleon",
    "amplified engineering",
    "amplã­a",
    "amplía",
    "ampotech",
    "ams ag",
    "amulet technologies",
    "amulyte",
    "amx (harman)",
    "amyx+",
    "anadigm",
    "analog devices, inc",
    "anantara solutions",
    "anaren",
    "anhui landunguang electronic co.,ltd. 安徽蓝盾光电子股份有限公司",
    "ansys",
    "antenova",
    "antmicro ltd",
    "anvyl",
    "anylink",
    "aopen",
    "apc",
    "api.ai (google)",
    "apio",
    "aplex",
    "apostera",
    "appclues infotech",
    "appdirect",
    "apple",
    "apple inc.",
    "applied informatics software engineering gmbh",
    "applied risk",
    "appliedmicro",
    "apprion (jacobs)",
    "apptimia",
    "apptricity",
    "appus studio lp",
    "aptomar",
    "apuqi",
    "apx labs",
    "aqrose technology",
    "aquamatix ltd.",
    "aquicore",
    "aranet",
    "aras corp",
    "arbor technology",
    "arcadia data",
    "arch systems",
    "archermind",
    "archos",
    "ardic",
    "arduino",
    "arecont vision",
    "arena",
    "arevo",
    "argus control systems",
    "argus cyber security",
    "argus embedded systems pvt ltd",
    "argustechnologies",
    "aricent",
    "aritime intelligent control",
    "arka infotech, llc",
    "arkados group",
    "arkessa",
    "arm",
    "armada chain",
    "armit co.",
    "array",
    "arrayent",
    "arrow electronics",
    "artesis a.s.",
    "artesyn embedded technologies",
    "aruba (hpe)",
    "aruba networks",
    "arundo analytics",
    "arviem",
    "arxan technologies",
    "aryballe technologies",
    "arynga, inc.",
    "asahi kasei microdevices",
    "asap systems",
    "asat tech",
    "asatech",
    "asavie",
    "ascalia",
    "ascom ag",
    "asi controls",
    "asset intertech",
    "asset mapping",
    "assetpulse",
    "astozi",
    "astralink",
    "astrata",
    "asus",
    "at&t",
    "atachi systems",
    "atheer",
    "athentek",
    "atmark techno",
    "atmel",
    "atollogy",
    "atom power",
    "atom robot",
    "atomiton",
    "atomiton, inc.",
    "atos",
    "atp electronics inc.",
    "attabotics",
    "attify",
    "attinad software",
    "atto technology, inc.",
    "augmate",
    "augmedix",
    "augment",
    "augmenta",
    "augmentastic private limited",
    "augmented pixels",
    "augmented radar imaging",
    "augury",
    "aurelius enterprise",
    "aurosys solutions, llc",
    "autec power systems",
    "autodesk",
    "autogrid",
    "automata",
    "automated logic corporation",
    "automation anywhere",
    "automatizacion corp",
    "automile",
    "autosys",
    "autotalks",
    "autotrip",
    "auvesy",
    "auxivo",
    "avalan wireless",
    "avalue technology",
    "avanade (accenture)",
    "avanade japan k.k.",
    "avantis (schneider electric)",
    "aveva",
    "avid solutions",
    "avm",
    "avnet",
    "avtech",
    "avx",
    "awcloud",
    "awen collective ltd",
    "awiatech",
    "axelerate solutions",
    "axiomtek",
    "axiros",
    "axis",
    "axis communications",
    "axonize",
    "axoom",
    "axoom (trumpf)",
    "axter agv",
    "ayla networks",
    "ayyeka",
    "azbil corporation",
    "azeti networks ag",
    "b konnet",
    "b scada",
    "b&k precision corporation",
    "b&p automation dynamics",
    "b&r industrial automation",
    "b-konnet",
    "b-scada",
    "bacnet stack at sourceforge",
    "bacsoft",
    "badgecontrol",
    "bae systems",
    "baidu",
    "baifendian",
    "baker hughes",
    "balluff",
    "bandweaver",
    "banyan water",
    "baosight",
    "baraja",
    "barbara iot",
    "barting",
    "basemark",
    "basen",
    "basler ag",
    "bastille networks",
    "batchmaster software",
    "baumer",
    "baumã¼ller",
    "baumüller",
    "bayshore networks, inc.",
    "bcfood erp",
    "bcm",
    "bdstar",
    "beach access software",
    "beacon 富士康",
    "beagleboard.org",
    "beamsmart",
    "beanair gmbh",
    "bebop sensors",
    "beckhoff",
    "beckwith electric",
    "bedrock automation",
    "beep networks",
    "beijing betaone sysjob",
    "beijing extech science&technology co.",
    "beijing hisign technology co., ltd. (hisign)",
    "beijing huatiehaixing",
    "beijing royaltech co., ltd",
    "beijing shooin technology  co.,ltd (休恩科技)",
    "bel power",
    "belden, inc.",
    "belkin",
    "benchmark electronics",
    "benewake",
    "berg insight",
    "berg london",
    "bestmile",
    "bevywise networks",
    "bics",
    "biduk electronic",
    "big belly",
    "bigip",
    "bigtera",
    "bio3d technologies",
    "biobots",
    "bit stew systems (ge digital)",
    "bitfidence",
    "bitreactive",
    "bivocom technologies",
    "biz4intellia",
    "bizinfor",
    "bizportals solutions",
    "black lake",
    "blackberry",
    "blesh",
    "blippar",
    "blonder tongue laboratories",
    "blue danube robotics",
    "blue link",
    "blue maestro",
    "blue pillar",
    "bluebotics",
    "bluecat networks",
    "bluecity",
    "bluegiga technologies",
    "bluetronics",
    "bluewrist",
    "bo'ge management consulting",
    "bocom",
    "boe technology",
    "boge group",
    "bohua technology",
    "bomgar",
    "boocax",
    "boonray",
    "bosch",
    "bosch connected devices and solutions gmbh",
    "bosch software innovations",
    "boston dynamics",
    "boundary devices",
    "bourns",
    "bouygues telecom",
    "boxie smart tech",
    "brady corporation",
    "brain corp",
    "bridgera llc",
    "bright machines",
    "bright wolf",
    "briq",
    "bristlecone",
    "broadcom",
    "broadlink",
    "broadsign international",
    "brock solutions",
    "brother",
    "bsi",
    "bsquare",
    "buddy platform",
    "bueno systems",
    "bug labs",
    "builder [x]",
    "buildingiq",
    "buildingminds",
    "buildsim",
    "built robotics",
    "bull (atos)",
    "bulldozair",
    "burndy llc",
    "busy bees acrylic displays co., ltd.",
    "buzz solutions",
    "byzoro networks",
    "c-labs",
    "c-labs corporation (trumpf)",
    "c2a security",
    "c2sense",
    "c3 iot",
    "ca technologies",
    "cadblu",
    "cadia networks",
    "caimore technology",
    "calamp",
    "calibre engineering",
    "california eastern laboratories (cel)",
    "cambium networks",
    "camio",
    "candi",
    "canon",
    "canonical group",
    "cantaloupe systems",
    "cantechs",
    "canvass analytics",
    "capgemini",
    "capital numbers infotech pvt ltd.",
    "capitoline",
    "capsule tech",
    "carbon3d",
    "carbynetech india",
    "cardy intelligent technology",
    "care innovations",
    "carel s.p.a.",
    "cargo chief",
    "cargosense",
    "cargotel",
    "cariq",
    "carnegie technologies",
    "carrier",
    "carrier corporation",
    "carriots",
    "caspel",
    "cassantec",
    "castor",
    "caterpillar inc.",
    "cavli wireless",
    "caxa",
    "caxa technology",
    "ccc software",
    "ccs inc.",
    "ccs-inc.",
    "celeno",
    "celestica",
    "cellfacts instruments",
    "cens data solutions private limited",
    "centri technology",
    "centurylink",
    "cermetek microelectronics",
    "cerrasystems",
    "certified security solutions",
    "ces   creative electronic systems",
    "ces - creative electronic systems",
    "cetec",
    "cgi",
    "chainvine",
    "chang hong technology co. ltd.",
    "chargepoint",
    "chassis plans, llc",
    "chatsworth products",
    "cherokee",
    "china hicloud",
    "china mobile",
    "china profound technology",
    "china telecom",
    "china telecom americas",
    "china transinfo",
    "chipkin automation systems",
    "chirp",
    "choice business connections",
    "chronocam",
    "ciara technologies",
    "cimon",
    "cinqueon",
    "circuitco",
    "circulor",
    "cirro",
    "cisco",
    "cisco jasper",
    "citelum",
    "cityworks",
    "cityzenith",
    "civicconnect",
    "civil maps",
    "clariion",
    "clarive software",
    "claroty",
    "clear object",
    "clearblade",
    "clearmetal",
    "clever cloud",
    "cleveroad",
    "clevest",
    "clientron corp.",
    "cllax",
    "clou iot technologies",
    "cloud of things",
    "cloudbackend",
    "cloudiip 东方国信",
    "cloudleaf",
    "cloudlock (cisco)",
    "cloudnc",
    "cloudplugs",
    "cloudsigma",
    "cloudwalk technology",
    "clx communications",
    "cml innovative technologies",
    "cmtl (computer memory test labs)",
    "cnlinko",
    "co trust",
    "co-trust",
    "coast 2 coast",
    "cobot",
    "codeit",
    "coderise",
    "codesys",
    "codian robotics",
    "cog",
    "cognex",
    "cognigy",
    "cognition",
    "cognizant",
    "cohda wireless",
    "cold chain sensors",
    "comark",
    "comau",
    "comfy",
    "comizoa",
    "common sensing",
    "commscope",
    "comnet europe limited",
    "comodule",
    "compology",
    "componentsoft",
    "compucom",
    "compulab",
    "computec oy",
    "computech",
    "comsol",
    "comtrol corporation",
    "concirrus",
    "concrete sensors",
    "conduce",
    "conergy",
    "conexant",
    "confidex",
    "congatec ag",
    "connect2.me (plasma business intelligence)",
    "connectavo",
    "connectblue",
    "connectedhealth",
    "connectedthinks",
    "connecthings",
    "connectm",
    "connectone",
    "connexxs",
    "connio",
    "connode",
    "conperio technology solutions",
    "const",
    "consyst",
    "contact software gmbh",
    "contec",
    "contemporary control systems",
    "contemporary controls",
    "contguard",
    "contrinex",
    "control applications ltd",
    "control solutions inc",
    "control4",
    "contus",
    "convercities",
    "converge",
    "coolmay",
    "cooper power systems (eaton)",
    "copa data",
    "copa-data",
    "coppelia robotics (blue workforce)",
    "core value",
    "corent technology inc.",
    "corerfid",
    "corlina",
    "cornell dubilier electronics",
    "corning optical communications",
    "corrosionradar",
    "cortexica vision systems",
    "corvalent corporation",
    "cosmoplat  海尔",
    "couchbase",
    "countbox",
    "coversant, inc.",
    "covisint",
    "cradlepoint",
    "cratedb",
    "cray inc.",
    "credo semiconductor",
    "cree",
    "crestron electronics",
    "crestron inc",
    "cristal controles",
    "critical link llc",
    "criticalblue",
    "cronj",
    "cross company",
    "crosscut",
    "crosser",
    "crosser technologies",
    "crouzet",
    "crowdinsight",
    "crowdstrike",
    "crunchtime",
    "crux photonics",
    "crystal clear technology sdn. bhd.",
    "crystalloids",
    "csb system ag",
    "csb-system ag",
    "csg",
    "cshark",
    "csic pride",
    "csk",
    "ctrack (inseego)",
    "cts corporation",
    "cubic",
    "cubilog ltd.",
    "cuelogic technologies",
    "cumulocity (software ag)",
    "curtiss-wright defense solutions",
    "custom software engineering",
    "cybera, inc",
    "cybergrx",
    "cybervision",
    "cyberx",
    "cybus",
    "cygnet infotech llc",
    "cyient",
    "cynlr",
    "cyphy systems",
    "cyphy works",
    "cypress envirosystems",
    "cypress semiconductor",
    "d link international",
    "d.fl",
    "dacom",
    "dahua technology",
    "daikin applied",
    "daintree networks (ge current)",
    "dairymac trackacow",
    "dali works",
    "dalian henryli",
    "dallas logic corporation",
    "daqri",
    "darktrace",
    "das writing services pvt. ltd.",
    "dasdata",
    "dash",
    "dashboard",
    "dashmote",
    "dassault systemes",
    "data hunter",
    "data modul ag",
    "datacor",
    "datagekko",
    "dataiku",
    "datalogic",
    "datamesh",
    "datanomix",
    "dataram",
    "datarobot",
    "datarpm",
    "datawatch",
    "datumize",
    "davra",
    "dawex",
    "dbsc",
    "dc square",
    "dc-square",
    "ddc i, inc",
    "ddc-i, inc",
    "ddriven solutions",
    "deacom, inc.",
    "decision software",
    "decisioniq",
    "decisions",
    "decisyon",
    "dedicated computing",
    "dedicated micros",
    "deep vision",
    "deepfield robotics (bosch)",
    "deepmind",
    "definium",
    "degson electronics",
    "dell",
    "dell boomi (dell)",
    "dell emc",
    "dell technologies",
    "deloitte llp",
    "delphi",
    "delta controls",
    "deltek",
    "dematic",
    "demc",
    "dennek",
    "densify",
    "denso wave incorporated",
    "deorwine infotech",
    "deos control systems gmbh",
    "derdack",
    "deutsche gesellschaft für internationale zusammenarbeit (giz) gmbh",
    "deutsche telekom",
    "dev technosys",
    "dev tecnologia",
    "device authority",
    "device solutions",
    "devicehive",
    "devicelynk",
    "devicepilot",
    "devicify",
    "devico solutions",
    "deyang equipment manufacturing iindustry cloud",
    "dfi inc.",
    "dglogik",
    "dgt",
    "dialight",
    "diamond point international",
    "difacto",
    "digabit",
    "digi",
    "digi-star",
    "digicert",
    "digiever corporation",
    "digilens",
    "digimondo gmbh",
    "digital alloys",
    "digital barriers",
    "digital china",
    "digital dreamworks",
    "digital factory (siemens)",
    "digital reach pvt.ltd",
    "digitalocean",
    "digiwin",
    "dimension automation",
    "dinkle",
    "diodes incorporated",
    "diota",
    "direct insight",
    "distech controls",
    "distence",
    "distributed services architecture (dsa)",
    "distribution one",
    "distrix networks",
    "dito",
    "dizmo",
    "dji",
    "dlink",
    "dobot",
    "doit international",
    "dojo by buguard",
    "doko tech",
    "domatica iot technology",
    "donghua testing technology",
    "donn technology",
    "doorport",
    "dorabot",
    "dorsavi",
    "dotdata",
    "douglas lighting controls",
    "dp technology",
    "dquid",
    "drag&bot",
    "draganfly",
    "draytek",
    "dreambox",
    "driblet labs",
    "drishti",
    "drone delivery canada",
    "drone logbook",
    "dronebase",
    "dronedeploy",
    "dscifer",
    "dtsl group",
    "dtx (contec)",
    "duali inc.",
    "dusun electron ltd",
    "duwei",
    "dux inc.",
    "dxc technology",
    "dynasign corporation",
    "dynastream",
    "e con systems",
    "e cube labs",
    "e-con systems",
    "e-cube labs",
    "e2v",
    "e4 engineering",
    "eagle",
    "eagle.io",
    "earlysense",
    "easyio",
    "easymile",
    "eaton",
    "eaton corporation",
    "ebn technology corp.",
    "echelon",
    "eci solutions",
    "eclipse iot",
    "ecomott inc.",
    "econais inc",
    "econet",
    "ecoplant",
    "ecorithm",
    "ecosense",
    "ecova",
    "eden worth pty ltd",
    "edensoft",
    "ederra technologies",
    "edge iintelligence",
    "edgewater networks",
    "edmi",
    "eduro ai",
    "edyza",
    "efy technology 一飞智控",
    "ehang",
    "ei3 corporation",
    "eigen innovations",
    "einfochips",
    "einfochips - iot services",
    "einride",
    "eiq",
    "eiratech robotics",
    "ekkono solutions",
    "elastic",
    "elecsys corporation",
    "electric imp",
    "eleks",
    "element ai",
    "element analytics",
    "element lab",
    "elesta gmbh",
    "eliftech",
    "elmo motion control",
    "elmodis",
    "else corp",
    "elster (honeywell)",
    "eltan bv",
    "eltav",
    "eltec elektronik ag",
    "embedded antenna design",
    "embedded planet",
    "embedded systems sia",
    "embedtec science & technology",
    "embedtek",
    "embedur",
    "embever gmbh",
    "embisphere",
    "emc",
    "emcraft systems",
    "emdoor information",
    "emerson",
    "emerson network power",
    "emitu",
    "emnify",
    "emote robotics ltd.",
    "emtoemgo ug (m2mgo)",
    "emulate 3d",
    "enbala power networks",
    "endian",
    "endiio ltd.",
    "endive software",
    "endress+hauser group",
    "enea",
    "energyrm",
    "energysavvy",
    "enernoc",
    "enertech",
    "enertrac",
    "enevo",
    "enging",
    "enisco",
    "enkay converged technologies llp",
    "enlight",
    "enlighted",
    "enmodus",
    "ennoconn",
    "enocean",
    "ensoft ltd",
    "entando",
    "enterpriseweb",
    "entes",
    "entic inc.",
    "entouch controls",
    "entrolink",
    "enviromon",
    "eon reality",
    "epidata, inc.",
    "episensor",
    "eplan",
    "epson",
    "equota energy",
    "erico",
    "ericsson",
    "eridanis",
    "escrypt (bosch)",
    "eseye",
    "esight energy",
    "espressif systems",
    "esri",
    "etrol",
    "eturns",
    "eura drives",
    "euro it group",
    "eurotech",
    "eventboard",
    "evercam",
    "everlight electronics",
    "everlytics data science",
    "eversec",
    "everysens",
    "evolveb.",
    "evothings",
    "evrythng",
    "evun",
    "ewatt technology co., ltd 易瓦特",
    "ewininfo",
    "ewon (hms industrial networks)",
    "exact",
    "exar (maxlinear)",
    "executive order",
    "exioms",
    "exor international s.p.a.",
    "exosite",
    "exotec solutions",
    "expemb",
    "extreme engineering solutions, inc. (x-es)",
    "fabric",
    "facexp",
    "faclon labs",
    "factory bucket",
    "factoryfour",
    "fairchild semiconductor international (on semiconductor)",
    "fairway electronic co. ltd",
    "falkonry",
    "faltcom",
    "fanuc america corporation",
    "far south networks",
    "fast radius",
    "fastable",
    "faststream technologies",
    "fathym",
    "fazezero",
    "feabhas",
    "feeney wireless (inseego)",
    "fero labs",
    "festo didactic",
    "fetch robotics",
    "fiberhome telecom tech",
    "fibocom",
    "fieldserver technologies",
    "fifo optics",
    "fiix software",
    "filament",
    "finebi",
    "finisar",
    "fireeye",
    "firetide",
    "firevisor",
    "firich enterprises",
    "first line software",
    "fischer block",
    "fisher smith",
    "fitivision",
    "five9 network systems, llc",
    "fiveai",
    "fivetran",
    "flaktwoods",
    "flame technology",
    "flatoak co., ltd.",
    "fleet space technologies",
    "fleetmatics",
    "flexciton",
    "flexem",
    "flexera software",
    "flexim",
    "flexis",
    "flexiv",
    "flextronic",
    "flexware innovation",
    "fliit",
    "flir",
    "flirtey",
    "flowgear",
    "fluence analytics",
    "fluidmesh networks",
    "fluke networks",
    "flutura",
    "flyingnets",
    "flytrex",
    "focus works",
    "focused photonics",
    "fogger",
    "foghorn",
    "foghub",
    "forcam",
    "forcecon",
    "forerock",
    "foresight robotics",
    "formlabs",
    "fos4x",
    "four faith smart power technology co., ltd",
    "four-faith smart power technology co., ltd",
    "foxconn",
    "foxtrot systems",
    "framos",
    "fraunhofer iosb",
    "freebsd",
    "freewave technologies",
    "freightverify",
    "freudenberg it (fit)",
    "friendly technologies",
    "ftdi chip",
    "fudan microelectronics group",
    "fuji electric",
    "fujian start computer equipment co., ltd.",
    "fujitsu",
    "fullrate",
    "fusient",
    "fusion connect",
    "fusionplant华为",
    "futuremove automotive",
    "futuretext",
    "fybr",
    "g element",
    "g7",
    "gadgeon systems inc",
    "gai tronics corporation",
    "gai-tronics corporation",
    "gainspan",
    "gallop engineering",
    "gambit communications",
    "gambit stream",
    "garo",
    "garrettcom",
    "gatherspace",
    "gauzy",
    "ge automation and controls (general electric)",
    "ge digital (ge)",
    "ge digital (general electric)",
    "gecko robotics",
    "gedae, inc.",
    "geek+",
    "gem analytics",
    "gemalto",
    "gemple m&e",
    "gemtek technology",
    "genband",
    "general cable",
    "general dynamics",
    "general electric (ge)",
    "general technics",
    "generic intelligent machines",
    "geneva systems",
    "genpact",
    "geopal solutions",
    "geoslam",
    "getac technology corporation",
    "getup cloud",
    "ghi electronics llc",
    "giatec scientific",
    "gigabyte",
    "gint",
    "gizwits",
    "glartek",
    "glass",
    "glassbeam",
    "gleechi",
    "glide technology pvt. ltd.",
    "global american, inc.",
    "global it app info solution",
    "global navigation systems",
    "globalflow",
    "globallogic",
    "globalsign inc.",
    "globeowl solutions inc.",
    "glue collaboration",
    "goexpedi",
    "goldenet",
    "gooee",
    "google",
    "grabit inc.",
    "grafana labs",
    "grammatech inc",
    "granite medsystems",
    "graphisoft",
    "grayhill",
    "greef",
    "green cloud technologies",
    "green hills software",
    "greenliant systems",
    "greenpeak technologies (qorvo)",
    "greenroad technologies",
    "greenwave systems",
    "greyorange",
    "grid connect, inc.",
    "gridpoint",
    "gridsense",
    "gridsmart",
    "ground inc.",
    "groundmetrics",
    "group-ib",
    "groupe renault",
    "grovestreams",
    "grovf",
    "growing energy labs inc (geli)",
    "guandata",
    "guangzhou navigateworx technologies co., ltd",
    "guardhat technologies",
    "guavus",
    "guide technology",
    "gumstix, inc",
    "guochuang software 科大国创软件股份有限公司",
    "gurus solutions",
    "gztech group",
    "göpel electronic gmbh",
    "h&d wireless",
    "h&t",
    "h3 dynamics holdings",
    "habx",
    "hacarus",
    "haier group",
    "hailo",
    "hal24k",
    "halo digital",
    "halo electronics",
    "haltian",
    "ham let",
    "ham-let",
    "hammond manufacturing",
    "hampoo",
    "hanasis",
    "hangmao stone marble granite co., ltd.",
    "hangzhou",
    "hanwei electronics",
    "happiest minds technologies",
    "hark.",
    "harley-davidson",
    "harman (samsung)",
    "harrington group international",
    "harris utilities",
    "harting technology group",
    "hcfa",
    "hcl technologies",
    "hd electric company",
    "hdim",
    "hectronic ab",
    "heidenhain",
    "hekr",
    "helium",
    "helium systems",
    "hellen technology",
    "henning software, inc.",
    "herames",
    "heroku",
    "hewlett packard enterprise (hpe)",
    "hezhisheng",
    "hi g tek",
    "hi-g-tek",
    "hibaosoft",
    "hibot",
    "hiconics",
    "hid global",
    "hidden brains infotech llc",
    "hikob",
    "hikvision",
    "hillsun",
    "hilscher system automation",
    "hirschmann (belden)",
    "hitachi",
    "hitachi data systems (hitachi)",
    "hitachi insight group (hitachi)",
    "hite",
    "hitseed",
    "hmicro",
    "hms",
    "hodusoft pvt. ltd.",
    "holl ipc technology co.,ltd",
    "hollysys",
    "holo-light",
    "holobuilder",
    "hologram",
    "holsys",
    "holt integrated circuits",
    "home assistant",
    "homebase",
    "hon hai precision",
    "honesty smart card",
    "honesty smart-card",
    "honeywell",
    "honeywell international",
    "honeywell international inc.",
    "horizon robotics",
    "hoteam software",
    "hp",
    "hqo",
    "hqsoftware",
    "hualong xunda information technology co., ltd",
    "huawei",
    "huazhi",
    "huazhi imt",
    "huazhong cnc",
    "huber+suhner",
    "huiling technology (hitbot)",
    "huiwu technologies",
    "hum industrial technology",
    "human condition safety",
    "humatics",
    "humaware",
    "huynew technology",
    "hydropoint data systems",
    "hyperstone gmbh",
    "hypr",
    "hyster",
    "hyster-yale",
    "i open innovations",
    "i-kingtec",
    "i.d. systems",
    "ia3 inc",
    "ibase technology",
    "ibhsoftec",
    "ibis networks",
    "ibm",
    "ibm watson (ibm)",
    "iconics",
    "iconics, inc.",
    "icop",
    "icp das",
    "ict automatisering nv",
    "icubed4",
    "idab",
    "idatase gmbh",
    "idealtech 翼动科技",
    "ideas2it technologies",
    "idm",
    "ids logic pvt. ltd.",
    "iei integration corp.",
    "iexec",
    "ifm efector",
    "ifs",
    "igologic, inc.",
    "iko innovations inc",
    "ils technology (telit)",
    "imec",
    "imi precision engineering",
    "impinj",
    "implico",
    "imron corporation",
    "imsolution",
    "imubit",
    "in-cloud 浪潮云",
    "indeema software inc.",
    "indegy",
    "indics 航天云网",
    "indicus software",
    "indie semiconductor",
    "indigoverge",
    "indu sol",
    "indu-sol",
    "inductive automation",
    "industrial analytics berlin iab gmbh",
    "industrial intelligence",
    "industrial internet consortium (iic)",
    "industrial network systems",
    "industrial vision systems",
    "industry manufacturing software",
    "ineda systems",
    "inelcom technology",
    "ineo-sense",
    "infineon",
    "infinias",
    "infinimesh inc.",
    "infinite uptime",
    "infinitet3ch",
    "infiswift",
    "inflectra",
    "inflowmatix",
    "infobionic",
    "infoblox",
    "infobright",
    "infoclutch",
    "infocus",
    "infomotion technology",
    "infor",
    "inforce computing",
    "informatica",
    "infortrend technology inc",
    "infosys",
    "infoteam software (suzhou)",
    "inga mbh",
    "ingenics",
    "ingenu",
    "inglobe",
    "ingshi",
    "initial state",
    "inlaylink",
    "innodisk",
    "innopath software",
    "innotech",
    "innovactive",
    "innovaide",
    "innovapptive",
    "innovasic",
    "innovax",
    "innoviz technologies",
    "innovizo",
    "inonet computer gmbh",
    "inovance technology",
    "inphi corporation",
    "inrix",
    "inside secure",
    "inspection2",
    "inspectorio",
    "inspiralia",
    "inspirient",
    "inspur",
    "instrumental",
    "insyde software",
    "insys icom",
    "intacct",
    "intamac",
    "intasoft",
    "integrated automation consulting",
    "integrateit",
    "intel",
    "intel data center manager (intel)",
    "intelbras",
    "intelind",
    "intellias",
    "intelliflux controls",
    "intellifusion",
    "intelligent structures",
    "intellinium",
    "intellisense.io",
    "intellisys consulting",
    "intematix corporation",
    "intento design",
    "intequus",
    "intercon",
    "interdigital",
    "interknowlogy",
    "intermatic",
    "interpolation",
    "intervalzero",
    "intraix",
    "intranav",
    "intrinsyc technologies corporation",
    "invengo",
    "invensense (tdk)",
    "invensys (schneider electric)",
    "inventec",
    "inventek systems",
    "invert robotics",
    "invia robotics",
    "invixium",
    "invoxia",
    "invt",
    "invt industrial technology",
    "io-3",
    "iobeam",
    "iobridge",
    "iocurrents, inc.",
    "iomote",
    "ionetworks",
    "ionsign oy",
    "iot chain",
    "iot dev labs",
    "iot factory",
    "iot systems inc.",
    "iot2cell",
    "iota",
    "iotblue",
    "iotconnect - industrial automation solution",
    "iotedge",
    "iotex",
    "iothink solutions",
    "iotium",
    "iotivity",
    "iotomation ecotech pvt. ltd.",
    "iotos",
    "iotw",
    "ipdatatel",
    "iptime",
    "iqeye",
    "iqms",
    "iqp corporation",
    "ircona",
    "irely",
    "irhythm technologies",
    "iris automation",
    "irise",
    "iron systems",
    "irootech",
    "is predict gmbh",
    "ism services, inc.",
    "issi integrated silicon solution inc.",
    "it vizion",
    "itac software ag",
    "itechart",
    "itexus",
    "itoris inc",
    "itron",
    "itw",
    "itw linx",
    "ivar jacobson",
    "iven",
    "ivprodukt",
    "iwave systems technologies",
    "iwerk solutions",
    "ixia",
    "ixon",
    "ixon b.v.",
    "ixsystem",
    "ixys corporation",
    "jabil",
    "janus remote communications (connor winfield corporation)",
    "janus remote communications (connor-winfield corporation)",
    "janz tec",
    "japan smart home market is an opportunity of usd 10.8 billion in 2025",
    "jci",
    "jelastic",
    "jerasoft",
    "jetway information",
    "jiangsu linyang energy co., ltd",
    "jikon",
    "jimu intelligent",
    "jingzhi  用友精智",
    "jiyi uav",
    "jkl components",
    "johanson dielectrics",
    "john deere",
    "johnson controls",
    "jolly technologies",
    "jouav",
    "joyent",
    "jtt",
    "jujotech",
    "jumper",
    "jungo",
    "juniper networks",
    "justsun heavy duty truck manufacturer co., ltd.",
    "jzaegis",
    "jztech",
    "k2data",
    "kaaiot technologies",
    "kaalot",
    "kaazing",
    "kabuku inc.",
    "kaeser compressors",
    "kagray",
    "kai square",
    "kaisi",
    "kalewa",
    "kalkitech",
    "kando",
    "kanhasoft",
    "kasda technologies",
    "kaspersky lab",
    "kaspersky lab uk ltd.",
    "kawasaki heavy industries",
    "kayadev ai",
    "kbc networks",
    "keb",
    "keba",
    "keepgo ltd",
    "keith & koep gmbh",
    "kellton tech solutions",
    "kelvin",
    "kemet corporation",
    "kenmei technologies",
    "kentix",
    "kepware (ptc)",
    "kernal automation company",
    "ketos",
    "keyasic",
    "keyedin",
    "keystone electronics",
    "kieback&peter gmbh&co kg",
    "kii",
    "kiloway",
    "kinco automation",
    "king pigeon communication.co.,ltd.",
    "kingbright",
    "kingdee",
    "kingston technology",
    "kitov systems",
    "kitu systems",
    "kiunsys",
    "kiwifarm",
    "klocwork",
    "kmc controls",
    "kmc controls inc.",
    "kneron",
    "koa speer electronics",
    "kodiak robotics",
    "kolmostar",
    "komfovent",
    "kone",
    "konekt",
    "konica minolta",
    "konkerlabs",
    "kontrol energy",
    "kontron",
    "konux",
    "kopin corporation",
    "kore wireless",
    "korea telecom",
    "kovio (thinfilm)",
    "koyo electronics",
    "kpmg",
    "ktcx",
    "kuangen communications",
    "kuangen network",
    "kudelski security",
    "kuka ag",
    "kule tech",
    "kura technologies",
    "kurnup",
    "kyland technology",
    "kübler group",
    "l&t technology services",
    "l.e.s.s.",
    "lab 651",
    "lab el",
    "lacie",
    "laird",
    "lancom systems",
    "landis+gyr",
    "languang innovative technology",
    "lanner electronics",
    "lantronix",
    "lapp group",
    "lattice semiconductor",
    "launchkey (iovation)",
    "lauterbach gmbh",
    "laxcen",
    "leadermes (emerald information systems ltd)",
    "leadshine automation technology",
    "leadshine technology",
    "leandna",
    "leanway",
    "leanworx technologies pvt.ltd",
    "legrand",
    "leightronix",
    "leizig",
    "lenovo",
    "leonardo company",
    "leuze electronic",
    "levadata",
    "levaux",
    "leverege",
    "leviton",
    "leviton mfg",
    "lewei 50",
    "lex computech",
    "lexi solutions",
    "lexmark",
    "lg",
    "lgcx",
    "libelium",
    "librestream",
    "lidar",
    "lidar 数字绿土",
    "liebherr group",
    "lifesize",
    "lilee systems",
    "linak",
    "linear technology",
    "ling frog",
    "lingxi",
    "link labs",
    "linksys",
    "linode",
    "linux foundation",
    "litbit",
    "lite on",
    "lite-on",
    "litemax",
    "litmus automation",
    "littelfuse",
    "litum",
    "living planit",
    "lkh precicon",
    "llamasoft",
    "locata",
    "locationguru solutions",
    "lochn",
    "locus technologies",
    "logic pd",
    "logic supply",
    "logicladder technologies",
    "logicline",
    "loginext",
    "logisense",
    "logmein",
    "logoit",
    "lokad",
    "longcom",
    "longcom iot",
    "longi engineering",
    "longsung technology",
    "looppay (samsung)",
    "lord microstrain",
    "losant",
    "loytec electronics gmbh",
    "lre solutions",
    "lsr (laird)",
    "lti motion",
    "lucata corporation",
    "lucid",
    "lucid design group",
    "lumasense technologies",
    "lumenradio",
    "lumex electrical & lighting solutions",
    "lumileds",
    "lutron",
    "lutron electronics co.",
    "luxoft",
    "lynx software technologies",
    "m&a technology",
    "m&m software",
    "m1 limited",
    "m2h global ltd",
    "m2m one",
    "m2mi corporation",
    "m2mlabs",
    "maana",
    "machfu",
    "machine-to-machine intelligence (m2mi)",
    "machinemetrics",
    "machineshop",
    "machstatz business solutions pvt. ltd.",
    "macronix",
    "maestro wireless solutions",
    "magedelight solutions pvt ltd",
    "magesolution",
    "magicplan",
    "magnachip semiconductor",
    "magnus group",
    "mainflux",
    "maintenel automation",
    "maisijie network",
    "make security technology",
    "makinarocks",
    "malong",
    "manifold",
    "mantle",
    "manudyn",
    "marble",
    "mariner",
    "marktgut",
    "marktrace",
    "mars tohken solutions (mts)",
    "marvell technology group",
    "mass automation",
    "masternaut",
    "materialise",
    "mathworks",
    "matternet",
    "maven machines",
    "maven wave",
    "mavoco ag",
    "maxbyte technologies",
    "maxon motor",
    "maxonic",
    "maygion",
    "mbx systems",
    "mbyte",
    "mcquay international",
    "mcube",
    "mdk gmbh",
    "mds technology",
    "me-automation projects (mitsubishi electric)",
    "medcrypt",
    "mediatek",
    "medium one",
    "megvii",
    "meltin mmi",
    "memex",
    "memsic",
    "memsql",
    "mender",
    "mentis services",
    "mentor graphics",
    "mercury systems",
    "meridian group international",
    "merit solutions",
    "meritdata",
    "mert software",
    "mesh systems",
    "meshdynamics",
    "meshify",
    "mestek",
    "mesur.io",
    "meti m2m india",
    "metromile",
    "metscale",
    "mettler toledo",
    "metz connect usa inc",
    "micro star international",
    "microchip technology",
    "microduino",
    "micromatch",
    "micron technology",
    "micropac industries",
    "microscan",
    "microsemi corporation",
    "microsoft",
    "microsoft azure",
    "midokura",
    "mikrotik",
    "milestone systems",
    "mill max",
    "mill-max",
    "millennial net",
    "mindtech consultancy",
    "mindtree",
    "ming jiang",
    "mingseal robotics",
    "minsait iot sofia2 (indra)",
    "miotlink",
    "miramems sensing technology co., ltd 明皜传感",
    "mirantis",
    "misurio ag",
    "misys manufacturing",
    "mitac",
    "miteno",
    "mitsubishi electric",
    "mitsubishi electric automation",
    "mitsubishi electric corporation",
    "mitsubishi heavy industries (mhi)",
    "mivors",
    "mixlinker",
    "mj intelligent system",
    "mlit solutions",
    "mmi",
    "mnubo",
    "mobica limited",
    "mobileye",
    "mobiloitte",
    "mocana",
    "mode",
    "modit 3d",
    "modius",
    "mojix",
    "molex",
    "momentum machines",
    "monixo",
    "monnit",
    "monolith",
    "moresoft",
    "motionloft",
    "motionminers",
    "motor power",
    "motorola",
    "motorola solutions",
    "movidius",
    "movilitas consulting",
    "movimento - acquired by delphi automotive plc",
    "movus",
    "moxa",
    "mpdv",
    "mprest",
    "msc technologies",
    "mtell (aspen technology)",
    "mueller electric company",
    "mujin, inc.",
    "multitech",
    "multitech systems",
    "murata manufacturing",
    "mutual mobile",
    "mxchip",
    "mxd",
    "myapps solutions",
    "mycelium networks (smartdatasystem)",
    "mydevices",
    "myir tech limited",
    "myrra",
    "mysphera",
    "n3n",
    "nanda automation",
    "nanjing byosoft",
    "nanoprecise sci corp",
    "nari group (state grid electric power research institute)",
    "nari technology",
    "narrativewave",
    "nasan solutions pvt ltd",
    "nasoftware",
    "nation e ltd",
    "nation-e ltd",
    "national instruments",
    "native robotics",
    "nauto",
    "navisite",
    "navvis",
    "nc tech",
    "nc-tech",
    "ncinga",
    "ncs technologies",
    "near miss management (nm)",
    "near-miss management (nm)",
    "nebbiolo technologies",
    "nec",
    "ned+ar display technology",
    "neebal technologies pvt ltd",
    "nefab",
    "neo4j",
    "neodian technology",
    "neousys technology",
    "neoway technology",
    "nervana systems",
    "nervedata",
    "nest (alphabet)",
    "net app",
    "netapp",
    "netdata",
    "netfoundry (tata communications)",
    "netgear",
    "netklass",
    "netmodule",
    "netradyne",
    "netronome",
    "netsurion",
    "network allies",
    "neucloud",
    "neul (huawei)",
    "neural concept",
    "neusoft",
    "neustar",
    "new boundary technologies",
    "new core tech",
    "new dimensions systems",
    "new generation sensors",
    "new hope",
    "newhope data",
    "newstart",
    "nexapp technologies pvt ltd",
    "nexcom",
    "nexgrid",
    "nexiilabs",
    "nexiona connectocrats",
    "nexleaf",
    "nexrev",
    "nextnine (honeywell international)",
    "ngenious solutions",
    "nginx",
    "ngrain corporation",
    "nichebees",
    "nido",
    "nimbelink",
    "nimblechapps",
    "niotek",
    "nivis",
    "nivus",
    "nkk switches",
    "nlp logix",
    "no magic",
    "noa labs",
    "nodka automation",
    "noguska",
    "nokia",
    "nomi",
    "nomura research institute (nri)",
    "noodle analytics, inc. (noodle.ai)",
    "norco habey",
    "norco-habey",
    "nordic semiconductor",
    "notifai",
    "novar",
    "novatel",
    "novatel wireless solutions (inseego)",
    "now micro, inc.",
    "nozomi networks",
    "npm",
    "nq mobile",
    "ntt data",
    "nubo software",
    "nucleus vision",
    "numem",
    "numerex",
    "nutanix",
    "nuuo",
    "nuvoton",
    "nvidia",
    "nvt",
    "nxp semiconductors",
    "nxtcontrol gmbh (schneider electric)",
    "nxxtech",
    "oberthur technologies",
    "objectfrontier software",
    "objectivity",
    "objects connected",
    "oblong industries",
    "obvius",
    "ocean data systems",
    "octavo labs",
    "octoblu (citrix)",
    "oden technologies",
    "oeesystems",
    "oemctrl",
    "okapi",
    "olympus corporation",
    "olympus sky technologies",
    "ombitron",
    "omega engineering",
    "omegacube",
    "omexell",
    "omni id",
    "omni m2m",
    "omni-id",
    "omni3d",
    "omniearth",
    "omnisci",
    "omron industrial automation",
    "on semiconductor",
    "ondaka",
    "one network",
    "onenet",
    "onetelecom.me",
    "onfarm systems",
    "onicon incorporated",
    "onion corporation",
    "onssi",
    "opendns (cisco)",
    "openhab",
    "openlegacy",
    "openpath",
    "openpicus",
    "openremote",
    "openstack",
    "opensynergy",
    "opentrends inc.",
    "optek technology",
    "opti (optirtc)",
    "optimal design",
    "optimum path",
    "optimus ride",
    "optiproerp",
    "opto 22",
    "opto22",
    "oracle",
    "orange",
    "orbiwise",
    "orientech",
    "orion labs",
    "orionm2m",
    "oryx embedded",
    "osaro",
    "osdb",
    "osisoft",
    "osnexus",
    "osprey informatics",
    "osram semiconductors",
    "ossisto 365",
    "other machine co.",
    "oton solutions",
    "otosense (analog devices)",
    "otto motors",
    "oue energy technology",
    "ouster",
    "outsmart power systems",
    "ovak technologies",
    "overland storage",
    "oxygis",
    "p a emilson",
    "p-a emilson",
    "pacific controls",
    "pactera",
    "pactera technologies",
    "palo alto networks",
    "panabit",
    "panasonic",
    "panduit",
    "pano logic",
    "panometric llc",
    "panoramic power",
    "paradata",
    "paraimpu",
    "pari robotics",
    "parker hannifin",
    "parkifi",
    "parpro systems",
    "particle",
    "pas",
    "passivsystems",
    "passkit",
    "pathpartner",
    "patient planet",
    "patriot technologies",
    "pch international",
    "pci lighting control systems",
    "pctel",
    "peak",
    "pegasystems",
    "pegatron",
    "peloton technology",
    "pensees",
    "pentamaster",
    "penteon corporation",
    "people and technology",
    "people power",
    "pepperl+fuchs",
    "pera global",
    "percepto",
    "perceptronics",
    "peregrine semiconductor",
    "perfectpattern gmbh",
    "perfectron",
    "pericom semiconductor",
    "pertino",
    "pessl instruments",
    "petasense",
    "petro-cyberworks information technology (pcitc)",
    "pfannenberg",
    "pfl supply",
    "phantom auto",
    "pharos production inc.",
    "phiar technologies, inc.",
    "philips",
    "philorise",
    "phoenix contact",
    "phoenix controls corporation",
    "phoenix energy technologies",
    "phoenix technologies",
    "phontinent technologies",
    "photoneo",
    "phunware",
    "physical web",
    "phytec",
    "phytoverse",
    "pickle robots",
    "pierbridge",
    "pingthings",
    "pinnacle data systems",
    "pinpoint information systems inc.",
    "pitney bowes",
    "pivotal (dell)",
    "pixeom",
    "pixus technologies",
    "placemeter",
    "planet",
    "planys technologies",
    "plat'home co., ltd.",
    "plat.one",
    "platformio",
    "plda",
    "plex systems",
    "plumchoice",
    "plumis",
    "plus one robotics",
    "plus.ai",
    "plutoshift",
    "plvision",
    "pny technologies",
    "pod group",
    "pointgrab",
    "polabs",
    "poladrone",
    "pollux automation",
    "polte",
    "polte corporation",
    "polycom",
    "polycore software",
    "polynetworks",
    "pomona electronics",
    "ponfac",
    "portwell",
    "pos software development company - i-verve inc",
    "power micro controls america",
    "powerit solutions",
    "pradotec",
    "prafly",
    "pratiti technologies",
    "precyse technologies",
    "predikto",
    "predixion (greenwave systems)",
    "preformed line products",
    "premio inc",
    "prescient",
    "presenso",
    "pressac",
    "pressac communications limited",
    "preteckt",
    "pricewaterhousecoopers",
    "primeton",
    "princeps",
    "prism skylabs",
    "prismlab china",
    "prismtech",
    "procad",
    "procera networks",
    "processpro",
    "prodrone",
    "prodsmart",
    "professional cooling & control systems",
    "professional systems associates",
    "profitkey international",
    "proglove",
    "project frog",
    "proleit",
    "promise technology inc.",
    "promisense 苏州诺联芯",
    "propergate",
    "prophesee",
    "prophetstor data services, inc.",
    "prostep inc",
    "prosyst (bosch)",
    "protech",
    "protech systems",
    "proudsmart cloud",
    "proxim wireless",
    "proximetry (relayr)",
    "prysmian group",
    "psc group, llc",
    "ptc",
    "ptgem pte ltd",
    "ptv planung transport verkehr ag",
    "pubnub",
    "pulse electronics corporation",
    "push technology",
    "qburst",
    "qianyuankunhe",
    "qingcloud",
    "qio technologies",
    "qliktag software",
    "qnap",
    "qnap systems",
    "qnx software systems",
    "qosmos",
    "qpoint robotic solutions",
    "qsan technology",
    "qsee",
    "qt",
    "quake global",
    "qualcomm",
    "quality by vision israel",
    "quanmax",
    "quant service",
    "quanta computer",
    "quectel",
    "questica eto",
    "qulix systems",
    "quuppa",
    "qylur intelligent systems",
    "r style",
    "r.stahl",
    "radcom",
    "radiall",
    "radiflow",
    "radio bridge, inc.",
    "radio frequency systems (rfs)",
    "radisys",
    "radley corporation",
    "rafi",
    "raima",
    "rain bird corporation",
    "ramco systems",
    "rapidvalue",
    "raritan",
    "rayven",
    "rcml robot control meta language",
    "re flekt",
    "re-flekt",
    "reach tech",
    "ready robotics",
    "real time automation",
    "real time innovations",
    "real time logic",
    "real time systems gmbh",
    "real-time innovations",
    "real-time systems gmbh",
    "realiteq",
    "reality ai",
    "realtek",
    "realtime robotics",
    "realtime technology",
    "realwear",
    "realwear, inc.",
    "rect",
    "recursion pharmaceuticals",
    "red alert labs",
    "red balloon security",
    "red dot robotics",
    "red hat",
    "redaptive",
    "redblack software",
    "redcom laboratories",
    "redknee",
    "redline communications",
    "redlion",
    "redpine signals",
    "redsalt",
    "reed",
    "reekoh",
    "reflex ces",
    "relayr",
    "relia software",
    "reliable controls corporation",
    "relimetrics",
    "reloc s.r.l.",
    "remote.it",
    "renesas electronics corporation",
    "renub research",
    "replicable technologies",
    "resin.io",
    "retailing connect-shanghai map data & tech incorporated",
    "rethink robotics",
    "revers.io",
    "revinfotech",
    "rewire security",
    "rexroth (bosch)",
    "rf code",
    "rf digital",
    "rhombus energy solutions, inc.",
    "ricoh",
    "ricoh company, ltd.",
    "rigado",
    "rigado llc",
    "rigol technologies, inc.",
    "riot",
    "rittal",
    "rivetz",
    "rle technologies",
    "rmus",
    "roadmap it solutions",
    "roadstar",
    "robocortex",
    "robocv",
    "robodev gmbh",
    "robodk",
    "robolab technologies pvt ltd",
    "robotic materials",
    "robotics technology leaders gmbh",
    "rockbay",
    "rockwell automation",
    "rodinbell technology co.,ltd",
    "rogers corporation",
    "rohm co., ltd.",
    "roima",
    "romaric corp (roth & rau)",
    "rombit",
    "room 5",
    "roomwizard",
    "rootcloud",
    "rootcloud 树根互联",
    "rootstock software",
    "rosch",
    "rostelecom",
    "routerboard",
    "routercad",
    "roving networks",
    "rovisys",
    "royal 4 systems",
    "rs monition",
    "rsa (dell)",
    "rstyle",
    "rta",
    "rtc manufacturing",
    "rtd embedded technologies",
    "rti",
    "rttech software",
    "rtx a/s",
    "rubicon global",
    "rubicon labs inc.",
    "ruff",
    "rulex",
    "runiot (opiron electronics)",
    "runma",
    "rushup srl",
    "rutone electronic",
    "s&c electric company",
    "s+p samson",
    "s3 id",
    "sadelabs",
    "safefleet",
    "safemode",
    "saffron technology (intel)",
    "sage erp solutions",
    "sage intelligent system",
    "sagemcom",
    "saildrone",
    "salesforce",
    "samay global",
    "samsara",
    "samsung electronics",
    "samsung semiconductor, inc. (ssi)",
    "samtec",
    "sanchuan",
    "sangfor",
    "sanken electric",
    "sanmina",
    "sany heavy industry",
    "sanyo denki",
    "sap",
    "sarcos",
    "sastrion",
    "satalia",
    "satixfy",
    "saudi telecom company solutions",
    "sauter",
    "savi technology (lockheed martin)",
    "saviant",
    "savioke",
    "sbs science & technology",
    "sbt",
    "scada vendor",
    "scadacore",
    "scandit",
    "scannex",
    "scarlet technologies",
    "schad",
    "schaffner",
    "schindler digital business ltd.",
    "schlumberger",
    "schmid technology systems",
    "schneider",
    "schneider electric",
    "schurter",
    "sciencesoft",
    "scientific green",
    "scinan iot",
    "sciyon",
    "scope ar",
    "scortex",
    "scribe software corporation",
    "scriptr.io",
    "scs swiss control systems",
    "sdchain",
    "se electronic",
    "se-elektronic",
    "seagate",
    "seagate technology",
    "seatone",
    "seco",
    "seco energy",
    "secomea",
    "secure meters",
    "securerf",
    "sedapta osys",
    "seebo",
    "seeq",
    "sefaira",
    "seisys",
    "sekmenler mak.müh.ağir san.mak.i̇th.i̇hç.ltd.şti̇.",
    "selc",
    "seluxit",
    "semicoa semiconductors",
    "semiotic labs",
    "semiprobe",
    "sempercon",
    "semtech",
    "semusi",
    "senaya",
    "seneca",
    "senet",
    "sensat",
    "sensativ",
    "sensavation",
    "sensee inc",
    "sensegrow",
    "sensemetrics",
    "sensetime",
    "sensewaves",
    "senseye",
    "sensing feeling",
    "sensity systems",
    "sensorbis gmbh",
    "sensorlogic (gemalto)",
    "sensors data",
    "sensorsuite",
    "sensoscientific",
    "sensr",
    "sensus",
    "sentilo",
    "sentinel ips",
    "sentrian",
    "sentrybay",
    "senvisys",
    "senzit",
    "sepio systems",
    "sercomm",
    "serious integrated, inc",
    "serotonin software technologies",
    "server technology",
    "servo-robot",
    "servotronix motion control",
    "sevnce",
    "sevone",
    "sevskiy gmbh",
    "sglab",
    "shadow creator",
    "shalaka technologies",
    "shandong cloud",
    "shanghai ingenious automation technology",
    "shanghai lanbao sensing technology",
    "shanghai linx valley system",
    "shanghai sunray information technology",
    "shanghai zhenhua heavy industry electric co., ltd",
    "sharp",
    "shengfeng",
    "shenyang machine tools",
    "shenzhen aerospace innotech corporation",
    "shenzhen ligent sensor tech (ligentcn)",
    "shenzhen lochn optics technology co.,ltd",
    "shenzhou aerospace software technology",
    "sherpa",
    "shidewei",
    "shine security",
    "shipcloud.io",
    "shipmonk",
    "shippeo",
    "shipwell",
    "shop edge software inc.",
    "shoptech software",
    "siasun",
    "sibotech automation",
    "sick",
    "siemens",
    "siemens building technologies",
    "siemens industry",
    "siemens industry inc.",
    "siemens technology to business (ttb) (siemens)",
    "sierra wireless",
    "sifteo",
    "sigband",
    "sigfox",
    "sight machine",
    "sightline systems",
    "signal cruncher",
    "signal garden",
    "signal integrity software, inc.",
    "signalogic",
    "silent sensors",
    "silex technology america",
    "silicom ltd",
    "silicon labs",
    "silicon motion technology",
    "silicondust",
    "silion technology",
    "silvair",
    "silver spring networks",
    "silverline",
    "sim technology",
    "simbe robotics",
    "simcom wireless solutions",
    "simevo s.r.l.",
    "simform",
    "simiplex technologies",
    "simple hardware",
    "simplecell networks",
    "simplesoft",
    "simplifier",
    "simularity",
    "simware solutions",
    "sine wave technologies",
    "sine-wave technologies",
    "singtel",
    "singularities",
    "sinomach",
    "sintef",
    "sirin software",
    "sirqul, inc",
    "site 1001",
    "siveco china",
    "sixdof space",
    "sixth energy technologies private limited",
    "sketchup",
    "skf",
    "skkynet",
    "sks kontakttechnik",
    "sky puzzle",
    "skybell",
    "skycatch",
    "skynet labs",
    "skyresponse",
    "slamtec",
    "sliontek",
    "slm solutions group ag",
    "slync.io",
    "smart plants",
    "smart sense d.o.o",
    "smart structures inc",
    "smart touch systems oü",
    "smart-tech controle e automação ltda",
    "smartb",
    "smartcap tech",
    "smartcloud",
    "smartcomm",
    "smarteam",
    "smartechs",
    "smarter sorting",
    "smartfab",
    "smartfactory",
    "smarthesia",
    "smartlog",
    "smartthings",
    "smartuc",
    "smartvue",
    "sml rfid",
    "smooth robotics",
    "sngular",
    "soce system on chip engineering",
    "soce system-on-chip engineering",
    "socomec",
    "sodacar",
    "soft robotics inc.",
    "softathome",
    "softdel",
    "softdesigners",
    "softech",
    "softeq",
    "softing",
    "softlink",
    "softnautics",
    "softomotive",
    "softserve",
    "software ag",
    "software motor company",
    "softwear automation",
    "solair (microsoft)",
    "solar log",
    "solcon",
    "solepower",
    "solidpartners",
    "solidrun ltd",
    "soloinsight",
    "solutions 4 iot",
    "somfy systems",
    "sonnet labs",
    "sonus",
    "sony",
    "sopheon",
    "sophic automation sdn bhd",
    "sophos",
    "sorba iot",
    "sos lab",
    "sourceday",
    "spaceage labs",
    "spaceti",
    "spacetime insight",
    "sparkcognition",
    "sparkl",
    "sparks dynamics",
    "spd ukraine",
    "spec india",
    "spectrum controls",
    "spectrum digital",
    "spectrum xli",
    "speedport",
    "speedshield technologies",
    "spensa",
    "spia",
    "spidergems",
    "spimesenselabs",
    "spindernet it solutions",
    "spinwave systems",
    "spirae llc",
    "splunk",
    "spotneats",
    "sprint",
    "spurit",
    "sst wireless",
    "sstcomm",
    "st engineering",
    "stackpole electronics",
    "stanley healthcare",
    "star",
    "starhub",
    "starship technologies",
    "starview international",
    "statwig",
    "steamaco",
    "steatite ltd",
    "stellapps technologies",
    "stm stieler",
    "stmicroelectronics",
    "stratoscale",
    "stream technologies",
    "streetline",
    "strella biotechnology",
    "striim",
    "strongarm tech",
    "sturfee",
    "subex ltd.",
    "sucheon",
    "sumeru verde technologies",
    "sumida automation",
    "sun microsystems",
    "suntek automation",
    "suntront",
    "sunward",
    "supcon group",
    "super micro computer",
    "supermicro",
    "superrfid",
    "supet阿里",
    "supply dynamics",
    "supplyshift",
    "supplystack",
    "surepark",
    "sureview instruments india",
    "surf communication solutions, ltd.",
    "swim.ai",
    "swissbit",
    "switch automation",
    "switchon",
    "swrve",
    "symantec",
    "symantec (a broadcom company)",
    "symbio robotics",
    "symg",
    "symplio",
    "synap iot",
    "synapse wireless",
    "synapt (prodapt)",
    "synapticon",
    "synchronic",
    "synergis software",
    "synfioo gmbh",
    "synlogics inc",
    "synology",
    "syntec technology",
    "sysmex",
    "syspro",
    "systema gmbh",
    "systium technologies",
    "t mobile",
    "t mobile austria gmbh",
    "t&w",
    "t-mobile",
    "t-mobile austria gmbh",
    "t-systems",
    "tachyus",
    "tacterion",
    "tag optics inc.",
    "taian",
    "taiwan semiconductor",
    "taiyo yuden",
    "talentcloud",
    "talkpool",
    "tandberg data",
    "taqua",
    "targetbay",
    "tas india pvt ltd",
    "tata communications",
    "tata consultancy services",
    "tatsoft",
    "td tech (nokia & huawei)",
    "tdinsights",
    "tdk",
    "te connectivity",
    "teamviewer",
    "teamvoy",
    "tech mahindra",
    "techavidus",
    "techbase",
    "techexcel",
    "techfin",
    "techman robot inc.",
    "technicolor",
    "technix technology (sayax)",
    "technosphere labs",
    "technoton engineering",
    "technowise",
    "tedalos",
    "tego",
    "telae asia",
    "telcare",
    "tele2",
    "teledyne technologies",
    "telefonica",
    "telemecanique",
    "telenor connexion",
    "telensa",
    "telesource communications inc.",
    "telezone",
    "telia",
    "telic ag",
    "telit",
    "telkonet",
    "tellabs",
    "telogis (verizon)",
    "telrad",
    "telstra",
    "teltonika",
    "temboo",
    "temp genius",
    "tempestive",
    "tempo automation",
    "tempoiq",
    "tenasys",
    "tend.ai",
    "tenda technology",
    "tendril",
    "teracode",
    "teradata",
    "teradeep",
    "terasic technologies",
    "terbine",
    "terepac",
    "tesla",
    "tetrascience",
    "texas instruments",
    "the apache software foundation",
    "the silicon partners",
    "the thing system",
    "theatro",
    "thecus",
    "thetaray",
    "thethings.io",
    "thinfilm electronics asa",
    "thing+",
    "thinger.io",
    "thinglogix",
    "thingsboard",
    "thingsquare",
    "thingstel",
    "thingstudio",
    "thingswise",
    "thingtech",
    "thingtrax",
    "thingworx",
    "think simple",
    "thinkforce",
    "thinkrise",
    "thomson data",
    "thoughtspot",
    "thoughtworks",
    "threeb it gmbh",
    "throughput",
    "thyssenkrupp",
    "tianchen electric",
    "tiandihexing",
    "tibbo system",
    "tibbo systems",
    "tidfore",
    "tiertime",
    "tieto",
    "tigergraph",
    "tivo",
    "tmc",
    "toa electronics, inc.",
    "tobii",
    "tokyo electron device ltd",
    "tongfang cloud computing technology",
    "top connect",
    "topper cam locks manufacturer co., ltd.",
    "topper ldpe pipe manufacturer co., ltd.",
    "toprie electronics",
    "topsec",
    "toradex",
    "tornado",
    "toshiba",
    "total phase, inc.",
    "touchnet technology",
    "toumetis",
    "toyota material handling europe",
    "tp link",
    "tp-link",
    "tplink",
    "tq systems",
    "tq-systems",
    "trane",
    "transatel",
    "transcend communication",
    "transformesh pte ltd",
    "transition networks",
    "transition technologies",
    "transvoyant",
    "transworld technologies ltd",
    "traqiq",
    "traverse",
    "trend",
    "trend control systems ltd",
    "trend micro",
    "trendchip",
    "trendminer",
    "trenton systems, inc.",
    "triacta power solutions lp",
    "triacta power solutions lp.",
    "triacta power tech. inc.",
    "triacta power technologies",
    "trianz",
    "tribal systems",
    "tridium",
    "tridium (honeywell)",
    "trilliant",
    "trillium incorporated",
    "trillium software (syncsort)",
    "trimble",
    "tripp lite",
    "trringo",
    "trueerp",
    "trumpf",
    "tttech",
    "tuev sued ag",
    "tulip interfaces",
    "turck",
    "turing robot",
    "turnsmith",
    "turvo",
    "tvs infotech",
    "twikit",
    "twin oaks computing",
    "twingz",
    "twixsoft llc",
    "tyan computer",
    "tyco",
    "u blox ag",
    "u-blox ag",
    "uavia",
    "ubeac",
    "ubidots",
    "ubiik",
    "ubimax",
    "ubiquiti networks",
    "ucloud",
    "ugmo technologies",
    "uhnder",
    "uhoo",
    "ul",
    "ul group",
    "ulalalab",
    "ume info",
    "umzuzu",
    "unabiz",
    "unicom engineering",
    "unidata",
    "unified inbox",
    "unifly",
    "unikey technologies",
    "union semiconductor",
    "unioncrate",
    "uniquid",
    "unisound",
    "unisys",
    "united electronic industries",
    "united technologies",
    "unitoon",
    "unitron",
    "unity consulting",
    "universal scientific industrial",
    "uposition",
    "upskill",
    "upskill (formerly apx labs)",
    "upswift",
    "uptake",
    "urbantz",
    "urbint",
    "urbiotica",
    "ursalink technology",
    "usens inc",
    "utilev",
    "utilidata",
    "utt technologies",
    "utthunga",
    "v2com",
    "vadatech inc.",
    "vai",
    "vaisto",
    "valarm",
    "valcom",
    "valify",
    "vantiq",
    "vantron",
    "vantron technology, ltd.",
    "variable",
    "variantz",
    "variscite",
    "varnish",
    "vdoo",
    "vechain",
    "vecoplan",
    "vecow",
    "vector",
    "vegam solutions",
    "veizu diagnosis",
    "velmenni",
    "velocio",
    "veniam",
    "venture corporation",
    "venture technologies",
    "veo robotics",
    "verdigris technologies",
    "veridify security",
    "veris industries",
    "verizon",
    "verna",
    "veros systems",
    "versafleet",
    "versalogic corp.",
    "versasense",
    "vertiai",
    "vg smartglass",
    "via",
    "viavi solutions",
    "vibrain solutions",
    "viconics technologies inc.",
    "videas",
    "view",
    "viezo",
    "viloc",
    "vinci digital",
    "vinnter",
    "virata",
    "virgil security",
    "vironit",
    "virtium llc",
    "virtium technology, inc.",
    "virtustream (dell)",
    "vishay",
    "vision lab apps",
    "visionflow",
    "visionmc",
    "visual communications company",
    "vital connect",
    "vitanet, inc.",
    "vividworks",
    "vivify health",
    "vizibl",
    "vizitech solutions",
    "vmware (dell)",
    "vocso technologies",
    "vodafone",
    "vodaphone",
    "volansys",
    "volex",
    "volocopter",
    "voltaic systems",
    "vrp consulting",
    "vs crm",
    "vultr",
    "vuzix",
    "vykon",
    "wabtec",
    "wadco business solutions pvt ltd",
    "wago",
    "wago kontakttechnik gmbh & co. kg",
    "wakecap technologies",
    "wamco",
    "wandelbots",
    "wapice ltd",
    "waterfall security solutions ltd",
    "watergroup pty. ltd",
    "waterloo software",
    "watersmart software",
    "wattstopper",
    "waveoptics",
    "wavetronix",
    "waviot",
    "waygum",
    "waygum inc.",
    "waylay",
    "wayray",
    "wazp",
    "wear",
    "weare",
    "weathermatic",
    "webalo",
    "webclues infotech",
    "webeasy",
    "webee",
    "webnms iot",
    "weg",
    "weightless sig",
    "weiss",
    "wellaware",
    "wellintech",
    "wellrain",
    "wems",
    "werma",
    "west valley digital technology",
    "westek technology ltd",
    "western digital",
    "wherescape",
    "whitewall energy",
    "whiznets",
    "whizpace pte ltd",
    "wi next",
    "wi-next",
    "wia",
    "wibu systems",
    "wibu-systems",
    "wikifactory",
    "wikitude",
    "win 911",
    "win enterprises",
    "win-911",
    "wind river",
    "wing",
    "wingtra",
    "winicssec technologies",
    "winmate communication inc",
    "winner micro",
    "winsystems",
    "winwire",
    "winzent technologies ab",
    "wipelot",
    "wipro",
    "wireless automation group",
    "wireless glue networks",
    "wireless sensors",
    "wireless tag",
    "wireless-tag",
    "wirepas",
    "wise systems",
    "wiser systems, inc.",
    "wistron corporation",
    "witekio",
    "witium",
    "wolkabout",
    "wonderlogix",
    "wonders information",
    "wonderware (schneider electric)",
    "workerbase",
    "workinman interactive llc",
    "works systems, inc",
    "workwise software",
    "worldaware",
    "worldsensing",
    "wovyn",
    "wrike",
    "wulian group",
    "wurldtech (ge digital)",
    "wurm",
    "wyconn",
    "wyless (kore)",
    "wysengine",
    "wyzbee (redpine signals)",
    "x-byte enterprise solutions",
    "xage security",
    "xarion laser acoustics",
    "xcube",
    "xebrium inc",
    "xellenz consulting",
    "xenoma",
    "xerafy",
    "xerox",
    "xfinity home (comcast)",
    "xiamen alotcer communication technology",
    "xiamen four faith communication technology co., ltd.",
    "xiamen four-faith communication technology co., ltd.",
    "xiaoi robot",
    "xilinx",
    "xively (google)",
    "xki",
    "xloong",
    "xmpro",
    "xoeye technologies",
    "xompass",
    "xped limited",
    "xpertrule software",
    "xreacloud 徐工信息汉云",
    "xunyi",
    "xyz reality",
    "xyz robotics",
    "yageo",
    "yakotec",
    "yale",
    "yandex data factory",
    "yanzi",
    "yaskawa electric corporation",
    "yaskawa vipa controls",
    "yazzoom",
    "yitu",
    "yodiwo",
    "yonyou",
    "yonyou network",
    "youpu communications",
    "yuemes",
    "yuneec 昊翔",
    "z3 technology, llc",
    "zab technologies",
    "zatar (zebra technologies)",
    "zebra technologies",
    "zeidman technologies",
    "zenatix",
    "zenner connect ag",
    "zenodys",
    "zensar technologies",
    "zenseio",
    "zensor",
    "zentri (silicon labs)",
    "zepp labs",
    "zerokey",
    "zerone consulting",
    "zerone consulting private limited",
    "zetta systems limited",
    "zf friedrichshafen ag",
    "zhizaoyun",
    "zhuge io",
    "ziasiot",
    "zillionsource technologies",
    "zin technologies",
    "zincfive",
    "zipit wireless, inc.",
    "zipline",
    "zira",
    "ziyan",
    "znyx networks, inc.",
    "zokin technology",
    "zolertia",
    "zones",
    "zonho electronics",
    "zonit structured solutions, llc",
    "zonoff",
    "zontec spc software",
    "zoomlion",
    "zoox",
    "zpmc",
    "zreyas technology",
    "zscaler",
    "zte",
    "zunch labs",
    "zymergen",
    "zyxel",
    "zühlke",
    "海致 bdp",
    ]